#!/bin/sh

if [ -z "$BASH_VERSION" ]; then
    exec bash "$0" "$@"
    exit 1  # Will only get here if exec itself fails to run
fi

if [ -f /etc/default/dse ]; then
  . /etc/default/dse
fi


if [ -z "$DSE_ENV" ]; then
    for include in "$DSE_HOME"/bin/dse-env.sh \
                   "$HOME/.dse-env.sh" \
                   "`dirname "$0"`/dse-env.sh" \
                   "/etc/dse/dse-env.sh"; do
        if [ -r "$include" ]; then
            DSE_ENV="$include"
            break
        fi
    done
fi

if [ -z "$DSE_ENV" ]; then
    echo "DSE_ENV could not be determined."
    exit 1
elif [ -r "$DSE_ENV" ]; then
    . "$DSE_ENV"
else
    echo "Location pointed by DSE_ENV not readable: $DSE_ENV"
    exit 1
fi


for dir in "$(dirname "$0")/../resources" \
            "$DSE_HOME/resources" \
            "/usr/share/dse" ; do
    if [ -f "$dir/dsbulk/bin/dsbulk" ]; then
      exec "$dir/dsbulk/bin/dsbulk" "$@"
    fi
done

echo "Cannot find dsbulk in DSE installation."
exit 1

# vi:ai sw=4 ts=4 tw=0 et
